import { Metadata } from 'next';
import { ScrollText, FileText, CheckCircle, Scale, ShieldCheck, Mail, Database, Globe } from 'lucide-react';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service | Anime Nation India',
  description: 'Terms of Service and conditions for using Anime Nation India.',
};

const termsData = [
  {
    title: "1. Acceptance of Terms",
    icon: <CheckCircle className="text-[#ff4dd2]" size={24} />,
    content: "By accessing, browsing, or using Anime Nation India (the \"Service\"), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must immediately discontinue your use of our platform. We reserve the right to update or modify these Terms at any time without prior notice. Your continued use of the Service after any changes indicates your acceptance of the new Terms."
  },
  {
    title: "2. User Accounts & Registration",
    icon: <ShieldCheck className="text-[#ff4dd2]" size={24} />,
    content: "Certain features of the Service may require you to register for an account. You are solely responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to provide accurate, current, and complete information during registration. Anime Nation India reserves the right to suspend or terminate accounts that provide false information, violate our Community Guidelines, or remain inactive for an extended period."
  },
  {
    title: "3. Intellectual Property Rights",
    icon: <Scale className="text-[#f47521]" size={24} />,
    content: "All content generated by the Anime Nation India team, including logos, visual design, text, and source code, are the exclusive property of Anime Nation India. However, anime titles, characters, cover images, synopsis text, and video trailers belong to their respective copyright holders, studios, and licensors. We utilize public APIs (AniList GraphQL, Jikan REST, YouTube) under fair use for educational and informational purposes as a database. We do not claim ownership over any licensed anime media."
  },
  {
    title: "4. Third-Party Services & APIs",
    icon: <Database className="text-[#ff4dd2]" size={24} />,
    content: "Our platform heavily relies on third-party APIs (such as AniList and Jikan) to provide anime data, character details, and statistics. We do not guarantee the 100% accuracy, completeness, or availability of this data. Additionally, any links or embedded video players (e.g., YouTube trailers) direct you to third-party services. We are not responsible for the content, privacy policies, or practices of any third-party websites or services."
  },
  {
    title: "5. User-Generated Content",
    icon: <ScrollText className="text-[#ff4dd2]" size={24} />,
    content: "Users may have the ability to post reviews, comments, or participate in forum discussions. By submitting content to Anime Nation India, you grant us a non-exclusive, worldwide, royalty-free license to use, display, reproduce, and distribute your content in connection with the Service. You are solely responsible for the content you post and must ensure it complies with our Community Guidelines (no hate speech, unauthorized spoilers, or explicit material)."
  },
  {
    title: "6. Acceptable Use Policy",
    icon: <Globe className="text-[#f47521]" size={24} />,
    content: "You agree not to misuse the Service or help anyone else do so. You must not attempt to breach security, reverse-engineer our platform, scrape data excessively without permission, spread malware, or engage in any activity that disrupts the experience of other users. Scraping our site for commercial purposes without explicit permission is strictly prohibited."
  },
  {
    title: "7. Disclaimer of Warranties",
    icon: <FileText className="text-gray-400" size={24} />,
    content: "Anime Nation India is provided on an \"AS IS\" and \"AS AVAILABLE\" basis. We expressly disclaim all warranties of any kind, whether express or implied, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not guarantee that the Service will be uninterrupted, secure, or error-free."
  },
  {
    title: "8. Limitation of Liability",
    icon: <Scale className="text-gray-400" size={24} />,
    content: "To the fullest extent permitted by applicable law, Anime Nation India and its developers shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service."
  }
];

export default function TermsPage() {
  const currentYear = new Date().getFullYear();

  return (
    <main className="min-h-screen bg-[#050716] pt-32 lg:pt-36 pb-20 relative overflow-hidden">
      {/* Background glow */}
      <div className="absolute top-0 right-1/4 w-[600px] h-[500px] bg-[#ff4dd2]/5 blur-[150px] rounded-full pointer-events-none" />
      <div className="absolute bottom-0 left-1/4 w-[600px] h-[500px] bg-[#f47521]/5 blur-[150px] rounded-full pointer-events-none" />

      {/* Grid overlay */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:24px_24px] pointer-events-none" />

      <div className="container mx-auto px-4 max-w-[900px] relative z-10">
        
        {/* Header Section */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center justify-center p-4 bg-[#12131A] rounded-2xl border border-[#2A2B30] mb-6 shadow-2xl">
            <ScrollText className="text-[#ff4dd2] size-12" />
          </div>
          <h1 className="text-4xl md:text-6xl font-black text-transparent bg-clip-text bg-gradient-to-r from-[#ff4dd2] via-[#ff6600] to-yellow-400 mb-4 uppercase tracking-tighter">
            Terms of Service
          </h1>
          <p className="text-[#a0a0a0] text-sm md:text-base font-semibold">
            Last Updated: <span className="text-white">June {currentYear}</span>
          </p>
        </div>

        {/* Introduction */}
        <div className="bg-[#12131A]/80 backdrop-blur-xl border border-[#2A2B30]/40 rounded-3xl p-6 md:p-8 mb-12 shadow-xl">
          <p className="text-[#E0E0E0] leading-relaxed text-base md:text-lg font-medium">
            Welcome to <strong className="text-white">Anime Nation India</strong>. These Terms of Service outline the rules, regulations, and legal agreements between you (the user) and Anime Nation India regarding the use of our database, discovery platform, and community forums. Please read these terms carefully.
          </p>
        </div>

        {/* Terms List */}
        <div className="space-y-8">
          {termsData.map((term, index) => (
            <div 
              key={index} 
              className="bg-[#121326]/60 backdrop-blur-xl border border-[#2A2B30]/40 rounded-3xl p-6 md:p-8 hover:border-[#ff4dd2]/30 transition-colors group shadow-lg"
            >
              <div className="flex items-center gap-4 mb-4">
                <div className="bg-[#12131A] p-3 rounded-xl border border-[#2A2B30]/50 group-hover:border-[#ff4dd2]/30 transition-colors shadow-lg">
                  {term.icon}
                </div>
                <h2 className="text-xl md:text-2xl font-bold text-white tracking-tight">
                  {term.title}
                </h2>
              </div>
              <div className="text-[#8A8A93] leading-relaxed text-sm md:text-base pl-0 md:pl-[4.5rem]">
                {term.content}
              </div>
            </div>
          ))}
        </div>

        {/* Contact Section */}
        <div className="mt-16 bg-gradient-to-br from-[#12131A] to-[#121326] border border-[#2A2B30]/50 rounded-3xl p-8 md:p-12 text-center shadow-2xl">
          <Mail className="text-[#ff4dd2] size-12 mx-auto mb-4" />
          <h2 className="text-2xl font-black text-white mb-4 uppercase tracking-wide">9. Contact Information</h2>
          <p className="text-[#a0a0a0] max-w-2xl mx-auto mb-6 text-sm md:text-base leading-relaxed">
            If you have any questions, concerns, or legal inquiries regarding these Terms of Service, please contact our support team. We aim to respond to all inquiries within 48 hours.
          </p>
          <Link 
            href="/contact" 
            className="inline-block bg-gradient-to-r from-[#ff4dd2]/20 to-[#f47521]/20 hover:from-[#ff4dd2]/30 hover:to-[#f47521]/30 border border-[#ff4dd2]/40 hover:border-[#ff4dd2]/60 text-white font-extrabold uppercase tracking-widest text-xs px-8 py-4 rounded-xl shadow-lg transition-all hover:scale-105 active:scale-95 cursor-pointer"
          >
            Contact Support
          </Link>
        </div>

        <div className="mt-12 text-center text-[#5A5A63] text-sm">
          <p>© {currentYear} Anime Nation India. All rights reserved.</p>
          <p className="mt-1">This document is not legal advice and is provided for informational purposes only.</p>
        </div>

      </div>
    </main>
  );
}
